
const quizData = [
    {
        question: "На сколько у вас прекрасный голос?",
        a: "1",
        b: "2",
        c: "3",
        d: "4",
        e: "5",
        f: "6",
        g: "7",
        h: "8",
        i: "9",
        j: "10",
        correct: "a",
        correct: "b",
        correct: "c",
        correct: "d",
        correct: "e",
        correct: "f",
        correct: "g",
        correct: "h",
        correct: "i",
        correct: "j"
    },
    {
        question: "На сколько вы отценили бы свой Танец?",
        a: "1",
        b: "2",
        c: "3",
        d: "4",
        e: "5",
        f: "6",
        g: "7",
        h: "8",
        i: "9",
        j: "10",
        correct: "a",
        correct: "b",
        correct: "c",
        correct: "d",
        correct: "e",
        correct: "f",
        correct: "g",
        correct: "h",
        correct: "i",
        correct: "j",
    },
    {
        question: "На сколько у вас прекрасный Дом?",
        a: "1",
        b: "2",
        c: "3",
        d: "4",
        e: "5",
        f: "6",
        g: "7",
        h: "8",
        i: "9",
        j: "10",
        correct: "a",
        correct: "b",
        correct: "c",
        correct: "d",
        correct: "e",
        correct: "f",
        correct: "g",
        correct: "h",
        correct: "i",
        correct: "j",
    },
    {
        question: "На сколько у вас прекрасная фигура?",
        a: "1",
        b: "2",
        c: "3",
        d: "4",
        e: "5",
        f: "6",
        g: "7",
        h: "8",
        i: "9",
        j: "10",
        correct: "a",
        correct: "b",
        correct: "c",
        correct: "d",
        correct: "e",
        correct: "f",
        correct: "g",
        correct: "h",
        correct: "i",
        correct: "j",
    },
    {
        question: "На сколько у вас хорошо здоровье?",
        a: "1",
        b: "2",
        c: "3",
        d: "4",
        e: "5",
        f: "6",
        g: "7",
        h: "8",
        i: "9",
        j: "10",
        correct: "a",
        correct: "b",
        correct: "c",
        correct: "d",
        correct: "e",
        correct: "f",
        correct: "g",
        correct: "h",
        correct: "i",
        correct: "j"
    },
    {
        question: "На сколько у вас много денег?",
        a: "1",
        b: "2",
        c: "3",
        d: "4",
        e: "5",
        f: "6",
        g: "7",
        h: "8",
        i: "9",
        j: "10",
        correct: "a",
        correct: "b",
        correct: "c",
        correct: "d",
        correct: "e",
        correct: "f",
        correct: "g",
        correct: "h",
        correct: "i",
        correct: "j",
    },
    {
        question: "На сколько вы счастливы?",
        a: "1",
        b: "2",
        c: "3",
        d: "4",
        e: "5",
        f: "6",
        g: "7",
        h: "8",
        i: "9",
        j: "10",
        correct: "a",
        correct: "b",
        correct: "c",
        correct: "d",
        correct: "e",
        correct: "f",
        correct: "g",
        correct: "h",
        correct: "i",
        correct: "j",
    },
    {
        question: "На сколько у вы умны?",
        a: "1",
        b: "2",
        c: "3",
        d: "4",
        e: "5",
        f: "6",
        g: "7",
        h: "8",
        i: "9",
        j: "10",
        correct: "a",
        correct: "b",
        correct: "c",
        correct: "d",
        correct: "e",
        correct: "f",
        correct: "g",
        correct: "h",
        correct: "i",
        correct: "j",
    },
    {
        question: "На сколько вы влиятельны?",
        a: "1",
        b: "2",
        c: "3",
        d: "4",
        e: "5",
        f: "6",
        g: "7",
        h: "8",
        i: "9",
        j: "10",
        correct: "a",
        correct: "b",
        correct: "c",
        correct: "d",
        correct: "e",
        correct: "f",
        correct: "g",
        correct: "h",
        correct: "i",
        correct: "j",
    },
    {
        question: "На сколько вы далеко живёте от дома?",
        a: "1",
        b: "2",
        c: "3",
        d: "4",
        e: "5",
        f: "6",
        g: "7",
        h: "8",
        i: "9",
        j: "10",
        correct: "a",
        correct: "b",
        correct: "c",
        correct: "d",
        correct: "e",
        correct: "f",
        correct: "g",
        correct: "h",
        correct: "i",
        correct: "j",
    },
];

export default quizData